// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CYDqLZBIh7Kf-6KBz8BH3jxgNmdOp0M',
    appId: '1:94075427150:web:1601bcb289a09d1126e61f',
    messagingSenderId: '94075427150',
    projectId: 'hyber-market-flutter',
    authDomain: 'hyber-market-flutter.firebaseapp.com',
    storageBucket: 'hyber-market-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlJE6AVPHTGTADlhGXfgE8wzIrzK-fps',
    appId: '1:94075427150:android:cab21f710bfa0b5126e61f',
    messagingSenderId: '94075427150',
    projectId: 'hyber-market-flutter',
    storageBucket: 'hyber-market-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvweHnbLKjMvm1-KcKmvCDG6L0VKKaibk',
    appId: '1:94075427150:ios:d54b2669a6443e3926e61f',
    messagingSenderId: '94075427150',
    projectId: 'hyber-market-flutter',
    storageBucket: 'hyber-market-flutter.firebasestorage.app',
    iosBundleId: 'com.example.hyberMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvweHnbLKjMvm1-KcKmvCDG6L0VKKaibk',
    appId: '1:94075427150:ios:d54b2669a6443e3926e61f',
    messagingSenderId: '94075427150',
    projectId: 'hyber-market-flutter',
    storageBucket: 'hyber-market-flutter.firebasestorage.app',
    iosBundleId: 'com.example.hyberMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6CYDqLZBIh7Kf-6KBz8BH3jxgNmdOp0M',
    appId: '1:94075427150:web:e52f6bdf20b8977826e61f',
    messagingSenderId: '94075427150',
    projectId: 'hyber-market-flutter',
    authDomain: 'hyber-market-flutter.firebaseapp.com',
    storageBucket: 'hyber-market-flutter.firebasestorage.app',
  );
}
